package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Competencia generated by hbm2java
 */
public class Competencia implements java.io.Serializable {

	private int id;
	private Deporte deporte;
	private Modalidad modalidad;
	private Sistemapuntuacion sistemapuntuacion;
	private Usuario usuario;
	private Date fechafin;
	private String reglamento;
	private String estado;
	private String nombre;
	private Date fechahorabajalogica;
	private Date fechainicio;
	private Set fixtures = new HashSet(0);
	private Set lugarrealizacions = new HashSet(0);
	private Set participantes = new HashSet(0);

	public Competencia() {
	}

	public Competencia(int id) {
		this.id = id;
	}

	public Competencia(int id, Deporte deporte, Modalidad modalidad, Sistemapuntuacion sistemapuntuacion,
			Usuario usuario, Date fechafin, String reglamento, String estado, String nombre, Date fechahorabajalogica,
			Date fechainicio, Set fixtures, Set lugarrealizacions, Set participantes) {
		this.id = id;
		this.deporte = deporte;
		this.modalidad = modalidad;
		this.sistemapuntuacion = sistemapuntuacion;
		this.usuario = usuario;
		this.fechafin = fechafin;
		this.reglamento = reglamento;
		this.estado = estado;
		this.nombre = nombre;
		this.fechahorabajalogica = fechahorabajalogica;
		this.fechainicio = fechainicio;
		this.fixtures = fixtures;
		this.lugarrealizacions = lugarrealizacions;
		this.participantes = participantes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Deporte getDeporte() {
		return this.deporte;
	}

	public void setDeporte(Deporte deporte) {
		this.deporte = deporte;
	}

	public Modalidad getModalidad() {
		return this.modalidad;
	}

	public void setModalidad(Modalidad modalidad) {
		this.modalidad = modalidad;
	}

	public Sistemapuntuacion getSistemapuntuacion() {
		return this.sistemapuntuacion;
	}

	public void setSistemapuntuacion(Sistemapuntuacion sistemapuntuacion) {
		this.sistemapuntuacion = sistemapuntuacion;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public String getReglamento() {
		return this.reglamento;
	}

	public void setReglamento(String reglamento) {
		this.reglamento = reglamento;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechahorabajalogica() {
		return this.fechahorabajalogica;
	}

	public void setFechahorabajalogica(Date fechahorabajalogica) {
		this.fechahorabajalogica = fechahorabajalogica;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public Set getFixtures() {
		return this.fixtures;
	}

	public void setFixtures(Set fixtures) {
		this.fixtures = fixtures;
	}

	public Set getLugarrealizacions() {
		return this.lugarrealizacions;
	}

	public void setLugarrealizacions(Set lugarrealizacions) {
		this.lugarrealizacions = lugarrealizacions;
	}

	public Set getParticipantes() {
		return this.participantes;
	}

	public void setParticipantes(Set participantes) {
		this.participantes = participantes;
	}

}
