package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Deporte generated by hbm2java
 */
public class Deporte implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set lugarrealizacions = new HashSet(0);
	private Set competencias = new HashSet(0);

	public Deporte() {
	}

	public Deporte(int id) {
		this.id = id;
	}

	public Deporte(int id, String nombre, Set lugarrealizacions, Set competencias) {
		this.id = id;
		this.nombre = nombre;
		this.lugarrealizacions = lugarrealizacions;
		this.competencias = competencias;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getLugarrealizacions() {
		return this.lugarrealizacions;
	}

	public void setLugarrealizacions(Set lugarrealizacions) {
		this.lugarrealizacions = lugarrealizacions;
	}

	public Set getCompetencias() {
		return this.competencias;
	}

	public void setCompetencias(Set competencias) {
		this.competencias = competencias;
	}

}
