package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Encuentro generated by hbm2java
 */
public class Encuentro implements java.io.Serializable {

	private int id;
	private Fecha fecha;
	private Participante participanteByIdparticipantea;
	private Participante participanteByIdparticipanteb;
	private Resultado resultado;
	private Boolean sepresentaa;
	private Boolean sepresentab;
	private Date fechaencuentro;
	private Encuentroeliminatoriadoble encuentroeliminatoriadoble;
	private Encuentroliga encuentroliga;
	private Set resultados = new HashSet(0);
	private Encuentroeliminatoriasimple encuentroeliminatoriasimple;

	public Encuentro() {
	}

	public Encuentro(int id) {
		this.id = id;
	}

	public Encuentro(int id, Fecha fecha, Participante participanteByIdparticipantea,
			Participante participanteByIdparticipanteb, Resultado resultado, Boolean sepresentaa, Boolean sepresentab,
			Date fechaencuentro, Encuentroeliminatoriadoble encuentroeliminatoriadoble, Encuentroliga encuentroliga,
			Set resultados, Encuentroeliminatoriasimple encuentroeliminatoriasimple) {
		this.id = id;
		this.fecha = fecha;
		this.participanteByIdparticipantea = participanteByIdparticipantea;
		this.participanteByIdparticipanteb = participanteByIdparticipanteb;
		this.resultado = resultado;
		this.sepresentaa = sepresentaa;
		this.sepresentab = sepresentab;
		this.fechaencuentro = fechaencuentro;
		this.encuentroeliminatoriadoble = encuentroeliminatoriadoble;
		this.encuentroliga = encuentroliga;
		this.resultados = resultados;
		this.encuentroeliminatoriasimple = encuentroeliminatoriasimple;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Fecha getFecha() {
		return this.fecha;
	}

	public void setFecha(Fecha fecha) {
		this.fecha = fecha;
	}

	public Participante getParticipanteByIdparticipantea() {
		return this.participanteByIdparticipantea;
	}

	public void setParticipanteByIdparticipantea(Participante participanteByIdparticipantea) {
		this.participanteByIdparticipantea = participanteByIdparticipantea;
	}

	public Participante getParticipanteByIdparticipanteb() {
		return this.participanteByIdparticipanteb;
	}

	public void setParticipanteByIdparticipanteb(Participante participanteByIdparticipanteb) {
		this.participanteByIdparticipanteb = participanteByIdparticipanteb;
	}

	public Resultado getResultado() {
		return this.resultado;
	}

	public void setResultado(Resultado resultado) {
		this.resultado = resultado;
	}

	public Boolean getSepresentaa() {
		return this.sepresentaa;
	}

	public void setSepresentaa(Boolean sepresentaa) {
		this.sepresentaa = sepresentaa;
	}

	public Boolean getSepresentab() {
		return this.sepresentab;
	}

	public void setSepresentab(Boolean sepresentab) {
		this.sepresentab = sepresentab;
	}

	public Date getFechaencuentro() {
		return this.fechaencuentro;
	}

	public void setFechaencuentro(Date fechaencuentro) {
		this.fechaencuentro = fechaencuentro;
	}

	public Encuentroeliminatoriadoble getEncuentroeliminatoriadoble() {
		return this.encuentroeliminatoriadoble;
	}

	public void setEncuentroeliminatoriadoble(Encuentroeliminatoriadoble encuentroeliminatoriadoble) {
		this.encuentroeliminatoriadoble = encuentroeliminatoriadoble;
	}

	public Encuentroliga getEncuentroliga() {
		return this.encuentroliga;
	}

	public void setEncuentroliga(Encuentroliga encuentroliga) {
		this.encuentroliga = encuentroliga;
	}

	public Set getResultados() {
		return this.resultados;
	}

	public void setResultados(Set resultados) {
		this.resultados = resultados;
	}

	public Encuentroeliminatoriasimple getEncuentroeliminatoriasimple() {
		return this.encuentroeliminatoriasimple;
	}

	public void setEncuentroeliminatoriasimple(Encuentroeliminatoriasimple encuentroeliminatoriasimple) {
		this.encuentroeliminatoriasimple = encuentroeliminatoriasimple;
	}

}
