package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Encuentroeliminatoriasimple generated by hbm2java
 */
public class Encuentroeliminatoriasimple implements java.io.Serializable {

	private int idencuentro;
	private Encuentro encuentro;
	private Encuentroeliminatoriasimple encuentroeliminatoriasimple;
	private Set encuentroeliminatoriasimples = new HashSet(0);

	public Encuentroeliminatoriasimple() {
	}

	public Encuentroeliminatoriasimple(Encuentro encuentro) {
		this.encuentro = encuentro;
	}

	public Encuentroeliminatoriasimple(Encuentro encuentro, Encuentroeliminatoriasimple encuentroeliminatoriasimple,
			Set encuentroeliminatoriasimples) {
		this.encuentro = encuentro;
		this.encuentroeliminatoriasimple = encuentroeliminatoriasimple;
		this.encuentroeliminatoriasimples = encuentroeliminatoriasimples;
	}

	public int getIdencuentro() {
		return this.idencuentro;
	}

	public void setIdencuentro(int idencuentro) {
		this.idencuentro = idencuentro;
	}

	public Encuentro getEncuentro() {
		return this.encuentro;
	}

	public void setEncuentro(Encuentro encuentro) {
		this.encuentro = encuentro;
	}

	public Encuentroeliminatoriasimple getEncuentroeliminatoriasimple() {
		return this.encuentroeliminatoriasimple;
	}

	public void setEncuentroeliminatoriasimple(Encuentroeliminatoriasimple encuentroeliminatoriasimple) {
		this.encuentroeliminatoriasimple = encuentroeliminatoriasimple;
	}

	public Set getEncuentroeliminatoriasimples() {
		return this.encuentroeliminatoriasimples;
	}

	public void setEncuentroeliminatoriasimples(Set encuentroeliminatoriasimples) {
		this.encuentroeliminatoriasimples = encuentroeliminatoriasimples;
	}

}
