package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fixture generated by hbm2java
 */
public class Fixture implements java.io.Serializable {

	private int id;
	private Competencia competencia;
	private Date fechacreacion;
	private Set fechas = new HashSet(0);

	public Fixture() {
	}

	public Fixture(int id) {
		this.id = id;
	}

	public Fixture(int id, Competencia competencia, Date fechacreacion, Set fechas) {
		this.id = id;
		this.competencia = competencia;
		this.fechacreacion = fechacreacion;
		this.fechas = fechas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Competencia getCompetencia() {
		return this.competencia;
	}

	public void setCompetencia(Competencia competencia) {
		this.competencia = competencia;
	}

	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	public Set getFechas() {
		return this.fechas;
	}

	public void setFechas(Set fechas) {
		this.fechas = fechas;
	}

}
