package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

/**
 * Modalidadliga generated by hbm2java
 */
public class Modalidadliga implements java.io.Serializable {

	private int idcompetencia;
	private Modalidad modalidad;
	private Boolean permiteempate;
	private Integer puntosporpresentarse;
	private Integer puntosporempate;
	private Integer puntosporganar;

	public Modalidadliga() {
	}

	public Modalidadliga(Modalidad modalidad) {
		this.modalidad = modalidad;
	}

	public Modalidadliga(Modalidad modalidad, Boolean permiteempate, Integer puntosporpresentarse,
			Integer puntosporempate, Integer puntosporganar) {
		this.modalidad = modalidad;
		this.permiteempate = permiteempate;
		this.puntosporpresentarse = puntosporpresentarse;
		this.puntosporempate = puntosporempate;
		this.puntosporganar = puntosporganar;
	}

	public int getIdcompetencia() {
		return this.idcompetencia;
	}

	public void setIdcompetencia(int idcompetencia) {
		this.idcompetencia = idcompetencia;
	}

	public Modalidad getModalidad() {
		return this.modalidad;
	}

	public void setModalidad(Modalidad modalidad) {
		this.modalidad = modalidad;
	}

	public Boolean getPermiteempate() {
		return this.permiteempate;
	}

	public void setPermiteempate(Boolean permiteempate) {
		this.permiteempate = permiteempate;
	}

	public Integer getPuntosporpresentarse() {
		return this.puntosporpresentarse;
	}

	public void setPuntosporpresentarse(Integer puntosporpresentarse) {
		this.puntosporpresentarse = puntosporpresentarse;
	}

	public Integer getPuntosporempate() {
		return this.puntosporempate;
	}

	public void setPuntosporempate(Integer puntosporempate) {
		this.puntosporempate = puntosporempate;
	}

	public Integer getPuntosporganar() {
		return this.puntosporganar;
	}

	public void setPuntosporganar(Integer puntosporganar) {
		this.puntosporganar = puntosporganar;
	}

}
