package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Modalidad generated by hbm2java
 */
public class Modalidad implements java.io.Serializable {

	private int id;
	private Boolean permiteempate;
	private Integer puntosporpresentar;
	private Integer puntosporempate;
	private Integer puntosporganar;
	private Set competencias = new HashSet(0);
	private Modalidadliga modalidadliga;
	private Modalidadeliminatoriasimple modalidadeliminatoriasimple;
	private Modalidadeliminatoriadoble modalidadeliminatoriadoble;

	public Modalidad() {
	}

	public Modalidad(int id) {
		this.id = id;
	}

	public Modalidad(int id, Boolean permiteempate, Integer puntosporpresentar, Integer puntosporempate,
			Integer puntosporganar, Set competencias, Modalidadliga modalidadliga,
			Modalidadeliminatoriasimple modalidadeliminatoriasimple,
			Modalidadeliminatoriadoble modalidadeliminatoriadoble) {
		this.id = id;
		this.permiteempate = permiteempate;
		this.puntosporpresentar = puntosporpresentar;
		this.puntosporempate = puntosporempate;
		this.puntosporganar = puntosporganar;
		this.competencias = competencias;
		this.modalidadliga = modalidadliga;
		this.modalidadeliminatoriasimple = modalidadeliminatoriasimple;
		this.modalidadeliminatoriadoble = modalidadeliminatoriadoble;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Boolean getPermiteempate() {
		return this.permiteempate;
	}

	public void setPermiteempate(Boolean permiteempate) {
		this.permiteempate = permiteempate;
	}

	public Integer getPuntosporpresentar() {
		return this.puntosporpresentar;
	}

	public void setPuntosporpresentar(Integer puntosporpresentar) {
		this.puntosporpresentar = puntosporpresentar;
	}

	public Integer getPuntosporempate() {
		return this.puntosporempate;
	}

	public void setPuntosporempate(Integer puntosporempate) {
		this.puntosporempate = puntosporempate;
	}

	public Integer getPuntosporganar() {
		return this.puntosporganar;
	}

	public void setPuntosporganar(Integer puntosporganar) {
		this.puntosporganar = puntosporganar;
	}

	public Set getCompetencias() {
		return this.competencias;
	}

	public void setCompetencias(Set competencias) {
		this.competencias = competencias;
	}

	public Modalidadliga getModalidadliga() {
		return this.modalidadliga;
	}

	public void setModalidadliga(Modalidadliga modalidadliga) {
		this.modalidadliga = modalidadliga;
	}

	public Modalidadeliminatoriasimple getModalidadeliminatoriasimple() {
		return this.modalidadeliminatoriasimple;
	}

	public void setModalidadeliminatoriasimple(Modalidadeliminatoriasimple modalidadeliminatoriasimple) {
		this.modalidadeliminatoriasimple = modalidadeliminatoriasimple;
	}

	public Modalidadeliminatoriadoble getModalidadeliminatoriadoble() {
		return this.modalidadeliminatoriadoble;
	}

	public void setModalidadeliminatoriadoble(Modalidadeliminatoriadoble modalidadeliminatoriadoble) {
		this.modalidadeliminatoriadoble = modalidadeliminatoriadoble;
	}

}
