package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set provincias = new HashSet(0);

	public Pais() {
	}

	public Pais(int id) {
		this.id = id;
	}

	public Pais(int id, String nombre, Set provincias) {
		this.id = id;
		this.nombre = nombre;
		this.provincias = provincias;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Set provincias) {
		this.provincias = provincias;
	}

}
