package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Participante generated by hbm2java
 */
public class Participante implements java.io.Serializable {

	private int id;
	private Competencia competencia;
	private String nombre;
	private String email;
	private Set encuentrosForIdparticipantea = new HashSet(0);
	private Renglontabla renglontabla;
	private Set encuentrosForIdparticipanteb = new HashSet(0);

	public Participante() {
	}

	public Participante(int id) {
		this.id = id;
	}

	public Participante(int id, Competencia competencia, String nombre, String email, Set encuentrosForIdparticipantea,
			Renglontabla renglontabla, Set encuentrosForIdparticipanteb) {
		this.id = id;
		this.competencia = competencia;
		this.nombre = nombre;
		this.email = email;
		this.encuentrosForIdparticipantea = encuentrosForIdparticipantea;
		this.renglontabla = renglontabla;
		this.encuentrosForIdparticipanteb = encuentrosForIdparticipanteb;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Competencia getCompetencia() {
		return this.competencia;
	}

	public void setCompetencia(Competencia competencia) {
		this.competencia = competencia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getEncuentrosForIdparticipantea() {
		return this.encuentrosForIdparticipantea;
	}

	public void setEncuentrosForIdparticipantea(Set encuentrosForIdparticipantea) {
		this.encuentrosForIdparticipantea = encuentrosForIdparticipantea;
	}

	public Renglontabla getRenglontabla() {
		return this.renglontabla;
	}

	public void setRenglontabla(Renglontabla renglontabla) {
		this.renglontabla = renglontabla;
	}

	public Set getEncuentrosForIdparticipanteb() {
		return this.encuentrosForIdparticipanteb;
	}

	public void setEncuentrosForIdparticipanteb(Set encuentrosForIdparticipanteb) {
		this.encuentrosForIdparticipanteb = encuentrosForIdparticipanteb;
	}

}
