package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia implements java.io.Serializable {

	private int id;
	private Pais pais;
	private String nombre;
	private Set localidads = new HashSet(0);

	public Provincia() {
	}

	public Provincia(int id) {
		this.id = id;
	}

	public Provincia(int id, Pais pais, String nombre, Set localidads) {
		this.id = id;
		this.pais = pais;
		this.nombre = nombre;
		this.localidads = localidads;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getLocalidads() {
		return this.localidads;
	}

	public void setLocalidads(Set localidads) {
		this.localidads = localidads;
	}

}
