package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

import java.util.Date;

/**
 * Registrosesion generated by hbm2java
 */
public class Registrosesion implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private Date horainicio;

	public Registrosesion() {
	}

	public Registrosesion(int id) {
		this.id = id;
	}

	public Registrosesion(int id, Usuario usuario, Date horainicio) {
		this.id = id;
		this.usuario = usuario;
		this.horainicio = horainicio;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getHorainicio() {
		return this.horainicio;
	}

	public void setHorainicio(Date horainicio) {
		this.horainicio = horainicio;
	}

}
