package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

/**
 * Renglontabla generated by hbm2java
 */
public class Renglontabla implements java.io.Serializable {

	private int idparticipante;
	private Participante participante;
	private Integer partidosempatados;
	private Integer partidosganados;
	private Integer tantosafavor;
	private Integer tantosencontra;
	private Integer partidosperdidos;

	public Renglontabla() {
	}

	public Renglontabla(Participante participante) {
		this.participante = participante;
	}

	public Renglontabla(Participante participante, Integer partidosempatados, Integer partidosganados,
			Integer tantosafavor, Integer tantosencontra, Integer partidosperdidos) {
		this.participante = participante;
		this.partidosempatados = partidosempatados;
		this.partidosganados = partidosganados;
		this.tantosafavor = tantosafavor;
		this.tantosencontra = tantosencontra;
		this.partidosperdidos = partidosperdidos;
	}

	public int getIdparticipante() {
		return this.idparticipante;
	}

	public void setIdparticipante(int idparticipante) {
		this.idparticipante = idparticipante;
	}

	public Participante getParticipante() {
		return this.participante;
	}

	public void setParticipante(Participante participante) {
		this.participante = participante;
	}

	public Integer getPartidosempatados() {
		return this.partidosempatados;
	}

	public void setPartidosempatados(Integer partidosempatados) {
		this.partidosempatados = partidosempatados;
	}

	public Integer getPartidosganados() {
		return this.partidosganados;
	}

	public void setPartidosganados(Integer partidosganados) {
		this.partidosganados = partidosganados;
	}

	public Integer getTantosafavor() {
		return this.tantosafavor;
	}

	public void setTantosafavor(Integer tantosafavor) {
		this.tantosafavor = tantosafavor;
	}

	public Integer getTantosencontra() {
		return this.tantosencontra;
	}

	public void setTantosencontra(Integer tantosencontra) {
		this.tantosencontra = tantosencontra;
	}

	public Integer getPartidosperdidos() {
		return this.partidosperdidos;
	}

	public void setPartidosperdidos(Integer partidosperdidos) {
		this.partidosperdidos = partidosperdidos;
	}

}
