package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Resultado generated by hbm2java
 */
public class Resultado implements java.io.Serializable {

	private int id;
	private Encuentro encuentro;
	private Date fecharegistro;
	private Resultadofinal resultadofinal;
	private Resultadoporsets resultadoporsets;
	private Resultadoporpuntuacion resultadoporpuntuacion;
	private Set encuentros = new HashSet(0);

	public Resultado() {
	}

	public Resultado(int id) {
		this.id = id;
	}

	public Resultado(int id, Encuentro encuentro, Date fecharegistro, Resultadofinal resultadofinal,
			Resultadoporsets resultadoporsets, Resultadoporpuntuacion resultadoporpuntuacion, Set encuentros) {
		this.id = id;
		this.encuentro = encuentro;
		this.fecharegistro = fecharegistro;
		this.resultadofinal = resultadofinal;
		this.resultadoporsets = resultadoporsets;
		this.resultadoporpuntuacion = resultadoporpuntuacion;
		this.encuentros = encuentros;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Encuentro getEncuentro() {
		return this.encuentro;
	}

	public void setEncuentro(Encuentro encuentro) {
		this.encuentro = encuentro;
	}

	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	public Resultadofinal getResultadofinal() {
		return this.resultadofinal;
	}

	public void setResultadofinal(Resultadofinal resultadofinal) {
		this.resultadofinal = resultadofinal;
	}

	public Resultadoporsets getResultadoporsets() {
		return this.resultadoporsets;
	}

	public void setResultadoporsets(Resultadoporsets resultadoporsets) {
		this.resultadoporsets = resultadoporsets;
	}

	public Resultadoporpuntuacion getResultadoporpuntuacion() {
		return this.resultadoporpuntuacion;
	}

	public void setResultadoporpuntuacion(Resultadoporpuntuacion resultadoporpuntuacion) {
		this.resultadoporpuntuacion = resultadoporpuntuacion;
	}

	public Set getEncuentros() {
		return this.encuentros;
	}

	public void setEncuentros(Set encuentros) {
		this.encuentros = encuentros;
	}

}
