package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

/**
 * Resultadoporpuntuacion generated by hbm2java
 */
public class Resultadoporpuntuacion implements java.io.Serializable {

	private int id;
	private Resultado resultado;
	private Integer puntajefinala;
	private Integer puntajefinalb;

	public Resultadoporpuntuacion() {
	}

	public Resultadoporpuntuacion(Resultado resultado) {
		this.resultado = resultado;
	}

	public Resultadoporpuntuacion(Resultado resultado, Integer puntajefinala, Integer puntajefinalb) {
		this.resultado = resultado;
		this.puntajefinala = puntajefinala;
		this.puntajefinalb = puntajefinalb;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Resultado getResultado() {
		return this.resultado;
	}

	public void setResultado(Resultado resultado) {
		this.resultado = resultado;
	}

	public Integer getPuntajefinala() {
		return this.puntajefinala;
	}

	public void setPuntajefinala(Integer puntajefinala) {
		this.puntajefinala = puntajefinala;
	}

	public Integer getPuntajefinalb() {
		return this.puntajefinalb;
	}

	public void setPuntajefinalb(Integer puntajefinalb) {
		this.puntajefinalb = puntajefinalb;
	}

}
