package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

/**
 * Resultadofinal generated by hbm2java
 */
public class Resultadofinal implements java.io.Serializable {

	private int id;
	private Resultado resultado;
	private Boolean empate;
	private Boolean ganaa;
	private Boolean ganab;

	public Resultadofinal() {
	}

	public Resultadofinal(Resultado resultado) {
		this.resultado = resultado;
	}

	public Resultadofinal(Resultado resultado, Boolean empate, Boolean ganaa, Boolean ganab) {
		this.resultado = resultado;
		this.empate = empate;
		this.ganaa = ganaa;
		this.ganab = ganab;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Resultado getResultado() {
		return this.resultado;
	}

	public void setResultado(Resultado resultado) {
		this.resultado = resultado;
	}

	public Boolean getEmpate() {
		return this.empate;
	}

	public void setEmpate(Boolean empate) {
		this.empate = empate;
	}

	public Boolean getGanaa() {
		return this.ganaa;
	}

	public void setGanaa(Boolean ganaa) {
		this.ganaa = ganaa;
	}

	public Boolean getGanab() {
		return this.ganab;
	}

	public void setGanab(Boolean ganab) {
		this.ganab = ganab;
	}

}
