package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

/**
 * Resultadoporsets generated by hbm2java
 */
public class Resultadoporsets implements java.io.Serializable {

	private int id;
	private Resultado resultado;
	private Integer puntosporabandono;
	private Sett sett;

	public Resultadoporsets() {
	}

	public Resultadoporsets(Resultado resultado) {
		this.resultado = resultado;
	}

	public Resultadoporsets(Resultado resultado, Integer puntosporabandono, Sett sett) {
		this.resultado = resultado;
		this.puntosporabandono = puntosporabandono;
		this.sett = sett;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Resultado getResultado() {
		return this.resultado;
	}

	public void setResultado(Resultado resultado) {
		this.resultado = resultado;
	}

	public Integer getPuntosporabandono() {
		return this.puntosporabandono;
	}

	public void setPuntosporabandono(Integer puntosporabandono) {
		this.puntosporabandono = puntosporabandono;
	}

	public Sett getSett() {
		return this.sett;
	}

	public void setSett(Sett sett) {
		this.sett = sett;
	}

}
