package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

/**
 * Sistemapuntuacionporpuntuacion generated by hbm2java
 */
public class Sistemapuntuacionporpuntuacion implements java.io.Serializable {

	private int idcompetencia;
	private Sistemapuntuacion sistemapuntuacion;
	private Integer puntosporabandono;

	public Sistemapuntuacionporpuntuacion() {
	}

	public Sistemapuntuacionporpuntuacion(Sistemapuntuacion sistemapuntuacion) {
		this.sistemapuntuacion = sistemapuntuacion;
	}

	public Sistemapuntuacionporpuntuacion(Sistemapuntuacion sistemapuntuacion, Integer puntosporabandono) {
		this.sistemapuntuacion = sistemapuntuacion;
		this.puntosporabandono = puntosporabandono;
	}

	public int getIdcompetencia() {
		return this.idcompetencia;
	}

	public void setIdcompetencia(int idcompetencia) {
		this.idcompetencia = idcompetencia;
	}

	public Sistemapuntuacion getSistemapuntuacion() {
		return this.sistemapuntuacion;
	}

	public void setSistemapuntuacion(Sistemapuntuacion sistemapuntuacion) {
		this.sistemapuntuacion = sistemapuntuacion;
	}

	public Integer getPuntosporabandono() {
		return this.puntosporabandono;
	}

	public void setPuntosporabandono(Integer puntosporabandono) {
		this.puntosporabandono = puntosporabandono;
	}

}
