package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

/**
 * Sistemapuntuacionporresultadofinal generated by hbm2java
 */
public class Sistemapuntuacionporresultadofinal implements java.io.Serializable {

	private int idcompetencia;
	private Sistemapuntuacion sistemapuntuacion;

	public Sistemapuntuacionporresultadofinal() {
	}

	public Sistemapuntuacionporresultadofinal(Sistemapuntuacion sistemapuntuacion) {
		this.sistemapuntuacion = sistemapuntuacion;
	}

	public int getIdcompetencia() {
		return this.idcompetencia;
	}

	public void setIdcompetencia(int idcompetencia) {
		this.idcompetencia = idcompetencia;
	}

	public Sistemapuntuacion getSistemapuntuacion() {
		return this.sistemapuntuacion;
	}

	public void setSistemapuntuacion(Sistemapuntuacion sistemapuntuacion) {
		this.sistemapuntuacion = sistemapuntuacion;
	}

}
