package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

/**
 * Sistemapuntuacionporsets generated by hbm2java
 */
public class Sistemapuntuacionporsets implements java.io.Serializable {

	private int idcompetencia;
	private Sistemapuntuacion sistemapuntuacion;
	private Integer cantidadmaximadesets;

	public Sistemapuntuacionporsets() {
	}

	public Sistemapuntuacionporsets(Sistemapuntuacion sistemapuntuacion) {
		this.sistemapuntuacion = sistemapuntuacion;
	}

	public Sistemapuntuacionporsets(Sistemapuntuacion sistemapuntuacion, Integer cantidadmaximadesets) {
		this.sistemapuntuacion = sistemapuntuacion;
		this.cantidadmaximadesets = cantidadmaximadesets;
	}

	public int getIdcompetencia() {
		return this.idcompetencia;
	}

	public void setIdcompetencia(int idcompetencia) {
		this.idcompetencia = idcompetencia;
	}

	public Sistemapuntuacion getSistemapuntuacion() {
		return this.sistemapuntuacion;
	}

	public void setSistemapuntuacion(Sistemapuntuacion sistemapuntuacion) {
		this.sistemapuntuacion = sistemapuntuacion;
	}

	public Integer getCantidadmaximadesets() {
		return this.cantidadmaximadesets;
	}

	public void setCantidadmaximadesets(Integer cantidadmaximadesets) {
		this.cantidadmaximadesets = cantidadmaximadesets;
	}

}
