package dominio2;
// Generated 8 oct. 2020 01:08:24 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int id;
	private Localidad localidad;
	private String dni;
	private String nombre;
	private String apellido;
	private String contrasenia;
	private String tipodocumento;
	private Set lugarrealizacions = new HashSet(0);
	private Set registrosesions = new HashSet(0);
	private Set competencias = new HashSet(0);

	public Usuario() {
	}

	public Usuario(int id) {
		this.id = id;
	}

	public Usuario(int id, Localidad localidad, String dni, String nombre, String apellido, String contrasenia,
			String tipodocumento, Set lugarrealizacions, Set registrosesions, Set competencias) {
		this.id = id;
		this.localidad = localidad;
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.contrasenia = contrasenia;
		this.tipodocumento = tipodocumento;
		this.lugarrealizacions = lugarrealizacions;
		this.registrosesions = registrosesions;
		this.competencias = competencias;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public String getTipodocumento() {
		return this.tipodocumento;
	}

	public void setTipodocumento(String tipodocumento) {
		this.tipodocumento = tipodocumento;
	}

	public Set getLugarrealizacions() {
		return this.lugarrealizacions;
	}

	public void setLugarrealizacions(Set lugarrealizacions) {
		this.lugarrealizacions = lugarrealizacions;
	}

	public Set getRegistrosesions() {
		return this.registrosesions;
	}

	public void setRegistrosesions(Set registrosesions) {
		this.registrosesions = registrosesions;
	}

	public Set getCompetencias() {
		return this.competencias;
	}

	public void setCompetencias(Set competencias) {
		this.competencias = competencias;
	}

}
